# Configuration for NIKKE Automation Framework

# Vision System Configuration
vision:
  capture:
    # Whether to use region of interest optimization
    use_roi: true
    # Default region to capture (left, top, width, height)
    # Set to null to capture the entire screen
    default_region: null
  
  template:
    # Base directory for template images
    base_dir: "resources/templates"
    # Default confidence threshold for template matching
    default_threshold: 0.8
    # Default matching method (EXACT, SQDIFF, CCORR)
    default_method: "EXACT"

# State Management Configuration
state:
  # History size for state tracking
  history_size: 50
  # Timeout for state transitions in seconds
  transition_timeout: 10.0
  # Whether to automatically recover from unknown states
  auto_recover: true

# Input Configuration
input:
  # Minimum delay between actions in seconds
  min_delay: 0.05
  # Maximum delay between actions in seconds
  max_delay: 0.2
  # Duration range for mouse movements (min, max) in seconds
  move_duration_range: [0.1, 0.3]
  # Whether to enable human-like mouse movement
  human_like_movement: true

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Directory for log files
  dir: "logs"
  # Log file name pattern
  file_pattern: "nikke_auto_{date}.log"
  # Maximum log file size in MB
  max_file_size: 10
  # Maximum number of log files to keep
  max_files: 5
  # Whether to log to console
  console_output: true

# Game-specific Configuration
game:
  # Screen resolution for the game
  resolution: [2560, 1440]
  # Aspect ratio mode
  aspect_ratio: "16:9"
  # List of states to check for auto-recovery
  critical_states:
    - "HOME_SCREEN"
    - "BATTLE"
    - "SHOP"
  # Maximum attempts for auto-recovery
  max_recovery_attempts: 3
